#!make
init:
	docker-compose exec phpfpm_newsio mkdir -p logs
	docker-compose exec phpfpm_newsio chmod -R 777 logs/

refresh:
	docker-compose exec phpfpm_newsio chmod -R 777 logs/

update:
	docker-compose exec phpfpm_newsio chmod -R 777 logs/
